### ISSUE TITLE
Some questions about codes the author released 

### ISSUE THREAD

**Issue by mumucc1** [LPengYang/MotionClone#18]
Great job! I would like to ask, where is the Location-Aware Semantic Guidance Module represented in the code? I couldn't find any reference to it. Thanks！

**Comment by LPengYang** [comment]
> Great job! I would like to ask, where is the Location-Aware Semantic Guidance Module represented in the code? I couldn't find any reference to it. Thanks！

Thansk for your attention on our work!  In the original verison, we employ Location-Aware Semantic Guidance for i) spatial layout perservation and ii) appearance perservation. In the current version, however, we remove Location-Aware Semantic Guidance and only perform motion guidance for motion cutomization, which enables faster generation speed with reduced memory comsumption.  This is because that in the current verison i) the motion gudiance from the same time-step provides substantial and consistent guidance intensity and ii) the motion guidance is only applied in up_block.1 (the original verison is applied in up_block.1  and up_block.2 for sufficient motion guidance) , which mainly captures the structure of each frame with less appearance effect. More detailes are available in the ablation study of the updated paper (https://arxiv.org/html/2406.05338v5).

**Comment by mumucc1** [comment]
OK Thanks！
